version: '3.8'

services:
  # Konfigurasi Database MySQL Khusus Portfolio
  db:
    image: mysql:8.0
    container_name: portfolio-mysql
    restart: always
    environment:
      # Password diambil otomatis dari file .env
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: portfolio_db
    # KITA HAPUS 'ports: 3306:3306' AGAR TIDAK BENTROK DENGAN MYSQL TAMANSARIKOST
    # Fitur 'expose' di bawah ini mengamankan MySQL murni hanya di dalam network docker
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Konfigurasi Backend NestJS
  api:
    build: .
    container_name: portfolio-backend
    restart: always
    ports:
      # KITA PAKAI PORT localhost:3005 DI VPS AGAR TIDAK BENTROK DENGAN PROJECT LAIN
      - "3005:3000"
    env_file:
      - .env
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db

volumes:
  mysql_data:
